language: cpp

compiler:
  - gcc

sudo: required
dist: trusty

env:
  - QT_BASE=48

before_install:
  - if [ "$QT_BASE" = "48" ]; then sudo add-apt-repository ppa:beineri/opt-qt487-trusty -y; fi
  - sudo apt-get update -qq

install:
  - if [ "$QT_BASE" = "48" ]; then sudo apt-get install -qq opt-qt4-qmake opt-qt4-dev-tools; source /opt/qt-4.8/bin/qt-4.8-env.sh; fi

script:
  - qmake -r
  - make
  - make check

notifications:
  email: true