######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 8 17:03:00 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += asitor.cpp
